### ISSUE TITLE
Fix encrypted logging

### ISSUE THREAD

**Issue by nopara73** [nopara73/MagicalCryptoWallet#17]
I have a general encrypy/decrypt function: StringCypher.  

It fails once in a while. Appveyor Windows logs:  

```
[xUnit.net 00:00:06.4325447]     CipherTests [FAIL]
[xUnit.net 00:00:06.4328704]       Assert.Throws() Failure
[xUnit.net 00:00:06.4329209]       Expected: typeof(System.Security.Cryptography.CryptographicException)
[xUnit.net 00:00:06.4329547]       Actual:   (No exception was thrown)
[xUnit.net 00:00:06.4338087]       Stack Trace:
[xUnit.net 00:00:06.4349705]         C:\projects\magicalcryptowallet\MagicalCryptoWallet.Tests\CryptoTests.cs(44,0): at MagicalCryptoWallet.Tests.CryptoTests.CipherTests()
Failed   CipherTests
Error Message:
 Assert.Throws() Failure
Expected: typeof(System.Security.Cryptography.CryptographicException)
Actual:   (No exception was thrown)
Stack Trace:
   at MagicalCryptoWallet.Tests.CryptoTests.CipherTests() in C:\projects\magicalcryptowallet\MagicalCryptoWallet.Tests\CryptoTests.cs:line 44
```

Possible way to reproduce it:

1. Write a test that assert throwing the CryptographicException many times and hope it'll fail once in a while, too.

**Comment by nopara73** [comment]
Just experienced the same on travis linux: https://travis-ci.org/nopara73/MagicalCryptoWallet/jobs/344706501

**Comment by lontivero** [comment]
The code is okay. The test is wrong because it makes the explicit assumption that when a wrong password is used it should always throw an exception (what it is incorrect). The code uses padding for encrypting and that padding is calculated based on the password so, most of the times (about 97% of the time) when the password is wrong it can not recalculate the padding in the chipherText. However, about 3% of the time it doesn't fail (even when the calculated padding is also wrong) and that's why the test fail.

To know if the message was encrypted with a given password we need to use authentication code. I will be pushing a version in minutes.

**Comment by nopara73** [comment]
https://github.com/nopara73/MagicalCryptoWallet/pull/29
