### ISSUE TITLE
Find the first ever bech32 transaction

### ISSUE THREAD

**Issue by nopara73** [nopara73/MagicalCryptoWallet#20]
Both on main and testnet. And update the readme of Backend:

> At initial syncronization the wallet must specify the hash of the first block that contains native segwit output. This hash must be hard coded into the client. (ToDo: find the hash.)

https://github.com/nopara73/MagicalCryptoWallet/blob/master/MagicalCryptoWallet.Backend/README.md

**Comment by lontivero** [comment]
SegWit was activated in [block 481824](https://blockchain.info/tx/dfcec48bb8491856c353306ab5febeb7e99e4d783eedf3de98f3ee0812b92bad) and that block has two p2wpkh txs:

[dfcec48bb8491856c353306ab5febeb7e99e4d783eedf3de98f3ee0812b92bad](https://blockchain.info/tx/dfcec48bb8491856c353306ab5febeb7e99e4d783eedf3de98f3ee0812b92bad) in block 0000000000000000001c8018d9cb3b742ef25114f27563e3fc4a1902167f9893
[f91d0a8a78462bc59398f2c5d7a84fcff491c26ba54c4833478b202796c8aafd](https://blockchain.info/tx/f91d0a8a78462bc59398f2c5d7a84fcff491c26ba54c4833478b202796c8aafd) in block 0000000000000000001c8018d9cb3b742ef25114f27563e3fc4a1902167f9893

I have to run my script against testnet in order to find the best p2wpk tx.

**Comment by lontivero** [comment]
In **testnet** the first segwit tx is
[b29fbe96bf737000f8e3536e9b4681a01b1ca6be3ac4bd1f8269cdbd465e6700](https://testnet.blockchain.info/tx/b29fbe96bf737000f8e3536e9b4681a01b1ca6be3ac4bd1f8269cdbd465e6700) found in block [00000000000f0d5edcaeba823db17f366be49a80d91d15b77747c2e017b8c20a](https://testnet.blockchain.info/block/00000000000f0d5edcaeba823db17f366be49a80d91d15b77747c2e017b8c20a)

<details><summary>Decoded Testnet3 Transaction</summary>

Using this service: https://live.blockcypher.com/btc/decodetx/ we get the following:

```json
{
    "addresses": [
        "1KoJ8Fpo2t8qg6V1t2qMc95DBb86pXVRio"
    ], 
    "block_height": -1, 
    "block_index": -1, 
    "confirmations": 0, 
    "double_spend": false, 
    "fees": 0, 
    "hash": "b29fbe96bf737000f8e3536e9b4681a01b1ca6be3ac4bd1f8269cdbd465e6700", 
    "inputs": [
        {
            "age": 0, 
            "output_index": 0, 
            "prev_hash": "74e29bb2338f7591d43ecf11c0694772c5ad371c722b0d153dfdf36e6ee8cc7f", 
            "script": "483045022100b7802669525f51f8a4ab7383fe9221d7d37c3e97cc63df78ccf194d313c1700b02201f8f89800624e6add482971d3d23677750dbe2f612b6fdff015bcaada1a2c02e012102f5463a5da2ea85339e1ec973b246720a1ad5dd57459d781b792bb9cc94180e77", 
            "script_type": "empty", 
            "sequence": 4294967295
        }
    ], 
    "outputs": [
        {
            "addresses": [
                "1KoJ8Fpo2t8qg6V1t2qMc95DBb86pXVRio"
            ], 
            "script": "76a914ce33b193c12f560d414ce51ff29f7e6cef01b81188ac", 
            "script_type": "pay-to-pubkey-hash", 
            "value": 487900000000
        }, 
        {
            "addresses": null, 
            "script": "0014751e76e8199196d454941c45d1b3a323f1433bd6", 
            "script_type": "pay-to-witness-pubkey-hash", 
            "value": 99000000
        }
    ], 
    "preference": "low", 
    "received": "2018-02-26T04:54:59.808228662Z", 
    "relayed_by": "54.167.27.185", 
    "size": 223, 
    "total": 487999000000, 
    "ver": 1, 
    "vin_sz": 1, 
    "vout_sz": 2
}
```
</details>
